// Contenu bilingue du portfolio. Modifie les champs fr / en pour ajuster les textes.

export const experiences = [
  {
    key: 'pfe',
    role: { fr: 'Stage PFE — Plateforme intelligente de recrutement', en: 'Final-year internship — Intelligent recruitment platform' },
    place: { fr: 'Projet de fin d\u2019études', en: 'Final-year project' },
    date: { fr: 'Février 2026', en: 'February 2026' },
    description: {
      fr: 'Conception et développement d\u2019une plateforme de recrutement basée sur une architecture microservices avec Spring Boot, Vue.js, MongoDB Atlas et Docker.',
      en: 'Design and development of a recruitment platform built on a microservices architecture with Spring Boot, Vue.js, MongoDB Atlas and Docker.',
    },
  },
  {
    key: 'onh',
    role: { fr: 'Stage d\u2019été — Site de formation interne', en: 'Summer internship — Internal training website' },
    place: { fr: 'Office National de l\u2019Huile, Tunis', en: 'Office National de l\u2019Huile, Tunis' },
    date: { fr: 'Juillet 2024', en: 'July 2024' },
    description: {
      fr: 'Stage d\u2019observation axé sur la création d\u2019un site web de formation interne et la découverte du fonctionnement administratif de l\u2019entreprise.',
      en: 'Observation internship focused on building an internal training website and learning the company\u2019s administrative operations.',
    },
  },
  {
    key: 'enactus',
    role: { fr: 'Secrétaire Générale', en: 'General Secretary' },
    place: { fr: 'Club Enactus Enicar', en: 'Enactus Enicar Club' },
    date: { fr: 'Février 2024', en: 'February 2024' },
    description: {
      fr: 'Coordination des membres et gestion des activités internes du club.',
      en: 'Coordinated club members and managed internal club activities.',
    },
  },
]

// Triés du plus récent au plus ancien
export const projects = [
  {
    key: 'recrutement',
    featured: true,
    status: 'local',
    date: { fr: 'Février 2026', en: 'February 2026' },
    name: 'Plateforme intelligente de recrutement',
    subtitle: { fr: 'Stage PFE', en: 'Final-year internship' },
    description: {
      fr: "Conception d'une plateforme de recrutement basée sur une architecture microservices. Analyse de CV et matching des profils via NLP (Llama 3.3, SBERT, TF-IDF, Naive Bayes), avec des dashboards interactifs pour visualiser les performances de recrutement.",
      en: 'Design of a recruitment platform built on a microservices architecture. CV analysis and profile matching using NLP (Llama 3.3, SBERT, TF-IDF, Naive Bayes), with interactive dashboards for recruitment analytics.',
    },
    stack: ['Spring Boot', 'Vue.js', 'MongoDB Atlas', 'Docker', 'NLP'],
    repo: '',
    demo: '',
  },
  {
    key: 'smartcity',
    status: 'local',
    date: { fr: 'Décembre 2025', en: 'December 2025' },
    name: 'Smart City — Services urbains interopérables',
    subtitle: { fr: 'Projet académique', en: 'Academic project' },
    description: {
      fr: "Plateforme intégrant 4 services web (REST, SOAP, GraphQL, gRPC) orchestrés via une API Gateway et déployés en microservices pour gérer mobilité, qualité de l'air et alertes urbaines.",
      en: 'Platform integrating 4 web services (REST, SOAP, GraphQL, gRPC) orchestrated through an API Gateway and deployed as microservices to manage mobility, air quality and urban alerts.',
    },
    stack: ['Spring Boot', 'REST/SOAP/GraphQL/gRPC', 'API Gateway', 'Docker'],
    repo: 'https://github.com/RtibiHana/smart-city-platform',
    demo: '',
  },
  {
    key: 'devops',
    status: 'local',
    date: { fr: 'Décembre 2025', en: 'December 2025' },
    name: 'End-to-End DevOps Project',
    subtitle: { fr: 'CI/CD & Kubernetes', en: 'CI/CD & Kubernetes' },
    description: {
      fr: "Automatisation du cycle de vie d'une API backend avec CI/CD, Docker et Kubernetes, incluant sécurité applicative (SAST/DAST) et observabilité.",
      en: 'Full lifecycle automation of a backend API with CI/CD, Docker and Kubernetes, including application security (SAST/DAST) and observability.',
    },
    stack: ['Docker', 'Kubernetes', 'CI/CD', 'SAST/DAST'],
    repo: '',
    demo: '',
  },
  {
    key: 'visionllm',
    status: 'local',
    date: { fr: 'Décembre 2025', en: 'December 2025' },
    name: 'Vision-LLM for Explainable Facial Emotion Recognition',
    subtitle: { fr: 'Projet académique — IA', en: 'Academic project — AI' },
    description: {
      fr: "Utilisation de modèles Vision-Language pour reconnaître et expliquer des émotions faciales composées à partir d'images annotées (RAF-CE).",
      en: 'Use of Vision-Language models to recognize and explain compound facial emotions from annotated images (RAF-CE).',
    },
    stack: ['Vision-Language Models', 'Computer Vision', 'Prompt Engineering'],
    repo: '',
    demo: '',
  },
  {
    key: 'forex',
    status: 'deployed',
    date: { fr: 'Été 2025', en: 'Summer 2025' },
    name: 'Forex Converter API',
    subtitle: { fr: 'Projet personnel', en: 'Personal project' },
    description: {
      fr: 'API REST de conversion de devises en temps réel, pensée pour être simple à intégrer et facile à déployer.',
      en: 'REST API for real-time currency conversion, designed to be simple to integrate and easy to deploy.',
    },
    stack: ['Spring Boot', 'REST API'],
    repo: 'https://github.com/RtibiHana/forex-converter-api',
    demo: '',
  },
  {
    key: 'snake',
    status: 'deployed',
    date: { fr: 'Été 2025', en: 'Summer 2025' },
    name: 'Snake — Design Patterns',
    subtitle: { fr: 'Projet académique — Java', en: 'Academic project — Java' },
    description: {
      fr: 'Jeu Snake développé en Java pour mettre en application des design patterns concrets : code pensé pour être extensible et maintenable.',
      en: 'Snake game built in Java to apply real design patterns: code designed to be extensible and maintainable.',
    },
    stack: ['Java', 'OOP', 'Design Patterns'],
    repo: 'https://github.com/RtibiHana/snake-design-patterns',
    demo: '',
  },
  {
    key: 'showgoon',
    status: 'local',
    date: { fr: 'Mai 2025', en: 'May 2025' },
    name: 'ShowGoOn',
    subtitle: { fr: 'Application mobile', en: 'Mobile app' },
    description: {
      fr: 'Application mobile pour consulter des spectacles et réserver en ligne, développée avec Android Studio et une base NoSQL.',
      en: 'Mobile app to browse live shows and book online, built with Android Studio and a NoSQL database.',
    },
    stack: ['Android Studio', 'NoSQL', 'Java'],
    repo: '',
    demo: '',
  },
  {
    key: 'glpi',
    status: 'local',
    date: { fr: 'Janvier 2025', en: 'January 2025' },
    name: 'Mise en place d\u2019un GLPI',
    subtitle: { fr: 'Projet académique', en: 'Academic project' },
    description: {
      fr: "Système de gestion du parc informatique mis en place avec GLPI, Docker et MariaDB.",
      en: 'IT asset management system set up using GLPI, Docker and MariaDB.',
    },
    stack: ['GLPI', 'Docker', 'MariaDB'],
    repo: '',
    demo: '',
  },
]

export const skills = [
  { group: { fr: 'Langages', en: 'Languages' }, items: ['Python', 'Java', 'C / C++', 'JavaScript'] },
  { group: { fr: 'Frontend', en: 'Frontend' }, items: ['Vue.js', 'Angular', 'HTML / CSS'] },
  { group: { fr: 'Backend', en: 'Backend' }, items: ['Spring Boot', 'Node.js', 'REST APIs'] },
  { group: { fr: 'Cloud & DevOps', en: 'Cloud & DevOps' }, items: ['AWS', 'Docker', 'Kubernetes', 'Git'] },
  { group: { fr: 'Bases de données', en: 'Databases' }, items: ['MySQL', 'Oracle', 'MongoDB'] },
  { group: { fr: 'IA & NLP', en: 'AI & NLP' }, items: ['LLM', 'NLP', 'Computer Vision'] },
]

export const certifications = [
  { name: 'AWS — Badge Amazon Web Services', date: { fr: 'Novembre 2025', en: 'November 2025' } },
  {
    name: { fr: 'NVIDIA — Fondamentaux de la Data Science Accélérée', en: 'NVIDIA — Fundamentals of Accelerated Data Science' },
    date: { fr: 'Décembre 2025', en: 'December 2025' },
  },
]

export const t = {
  fr: {
    greeting: 'Bonjour, je suis',
    role: 'Ingénieure en Génie Informatique',
    status: 'disponible pour une opportunité',
    heroLead:
      "Ingénieure diplômée, j'ai conçu et développé une plateforme intelligente de recrutement combinant microservices Spring Boot, Vue.js et IA générative pour mon PFE. Certifiée AWS, passionnée par le Cloud Computing et le DevOps, je recherche mon premier poste.",
    viewProjects: 'Voir les projets',
    contactMe: 'Me contacter',
    navExperience: 'Expérience',
    navProjects: 'Projets',
    navSkills: 'Compétences',
    navAbout: 'Profil',
    navContact: 'Contact',
    experienceEyebrow: 'Parcours',
    experienceTitle: 'Expérience',
    projectsEyebrow: 'Projets',
    projectsTitle: 'Ce que j\u2019ai construit',
    featuredLabel: 'Projet phare',
    skillsEyebrow: 'Compétences',
    skillsTitle: 'La stack',
    aboutEyebrow: 'Profil',
    aboutTitle: 'En bref',
    aboutText:
      "Ingénieure en Génie Informatique diplômée de l'École Nationale d'Ingénieurs de Carthage, passionnée par le développement logiciel et les technologies innovantes. Mon projet de fin d'études — une plateforme intelligente de recrutement combinant Spring Boot, Vue.js et IA générative — reflète mon goût pour les architectures modernes et l'IA appliquée. Certifiée AWS, je m'intéresse particulièrement au Cloud Computing et au DevOps.",
    certsTitle: 'Certifications',
    contactEyebrow: 'Contact',
    contactTitle: 'Discutons',
    contactText: "Ouverte à toute opportunité de premier poste en développement full-stack ou cloud/DevOps.",
    cvFr: 'CV — Français',
    cvEn: 'CV —  Anglais',
    repoLink: 'Code source ↗',
    demoLink: 'Démo live ↗',
    linkSoon: 'Lien à venir',
    footerNote: 'construit avec Vue.js',
  },
  en: {
    greeting: "Hi, I'm",
    role: 'Computer Engineer',
    status: 'available for opportunities',
    heroLead:
      "Graduate engineer, I designed and built an intelligent recruitment platform combining Spring Boot microservices, Vue.js and generative AI for my final-year project. AWS certified, with a strong interest in Cloud Computing and DevOps, looking for my first position.",
    viewProjects: 'View projects',
    contactMe: 'Contact me',
    navExperience: 'Experience',
    navProjects: 'Projects',
    navSkills: 'Skills',
    navAbout: 'About',
    navContact: 'Contact',
    experienceEyebrow: 'Background',
    experienceTitle: 'Experience',
    projectsEyebrow: 'Projects',
    projectsTitle: 'What I\u2019ve built',
    featuredLabel: 'Flagship project',
    skillsEyebrow: 'Skills',
    skillsTitle: 'The stack',
    aboutEyebrow: 'About',
    aboutTitle: 'In short',
    aboutText:
      "Computer Engineer graduate from ENICarthage, passionate about software development and emerging technologies. My final-year project — an intelligent recruitment platform combining Spring Boot, Vue.js and generative AI — reflects my interest in modern architectures and applied AI. AWS certified, with a strong interest in Cloud Computing and DevOps.",
    certsTitle: 'Certifications',
    contactEyebrow: 'Contact',
    contactTitle: "Let's talk",
    contactText: 'Open to first full-time opportunities in full-stack development or cloud/DevOps.',
    cvFr: 'Resume — French',
    cvEn: 'Resume — English',
    repoLink: 'Source code ↗',
    demoLink: 'Live demo ↗',
    linkSoon: 'Link coming soon',
    footerNote: 'built with Vue.js',
  },
}